package simpledb;
import java.util.*;

/**
 * The Join operator implements the relational join operation.
 */
public class Join extends AbstractDbIterator {

    private JoinPredicate p;

    private DbIterator child1;

    private DbIterator child2;

    private Tuple tuple1;

    private TupleDesc tupleDesc;

    private int numField1;

    private int numField2;

    /**
     * Constructor.  Accepts to children to join and the predicate
     * to join them on
     *
     * @param p The predicate to use to join the children
     * @param child1 Iterator for the left(outer) relation to join
     * @param child2 Iterator for the right(inner) relation to join
     */
    public Join(JoinPredicate p, DbIterator child1, DbIterator child2) {
        // some code goes here
        this.p = p;
        this.child1 = child1;
        this.child2 = child2;
        this.numField1 = child1.getTupleDesc().numFields();
        this.numField2 = child2.getTupleDesc().numFields();
        this.tupleDesc = TupleDesc.combine(this.child1.getTupleDesc(), this.child2.getTupleDesc());
    }

    /**
     * @see simpledb.TupleDesc#combine(TupleDesc, TupleDesc) for possible implementation logic.
     */
    public TupleDesc getTupleDesc() {
        // some code goes here
        return this.tupleDesc;
    }

    public void open()
        throws DbException, NoSuchElementException, TransactionAbortedException {
        // some code goes here
        this.child1.open();
        this.child2.open();
        this.tuple1 = this.child1.hasNext() ? this.child1.next() : null;
    }

    public void close() {
        // some code goes here
        child1.close();
        child2.close();
    }

    public void rewind() throws DbException, TransactionAbortedException {
        // some code goes here
        child1.rewind();
        child2.rewind();
        this.tuple1 = this.child1.hasNext() ? this.child1.next() : null;
    }

    /**
     * Returns the next tuple generated by the join, or null if there are no more tuples.
     * Logically, this is the next tuple in r1 cross r2 that satisfies the join
     * predicate.  There are many possible implementations; the simplest is a
     * nested loops join.
     * <p>
     * Note that the tuples returned from this particular implementation of
     * Join are simply the concatenation of joining tuples from the left and
     * right relation. Therefore, if an equality predicate is used 
     * there will be two copies of the join attribute
     * in the results.  (Removing such duplicate columns can be done with an
     * additional projection operator if needed.)
     * <p>
     * For example, if one tuple is {1,2,3} and the other tuple is {1,5,6},
     * joined on equality of the first column, then this returns {1,2,3,1,5,6}.
     *
     * @return The next matching tuple.
     * @see JoinPredicate#filter
     */
    protected Tuple readNext() throws TransactionAbortedException, DbException {
        // some code goes here
        while (this.tuple1 != null) {
            Tuple tuple2;
            while (this.child2.hasNext()) {
                tuple2 = this.child2.next();
                if (this.p.filter(this.tuple1, tuple2)) {
                    Tuple t = new Tuple(this.getTupleDesc());
                    for (int i = 0; i != this.numField1; ++i) {
                        t.setField(i, this.tuple1.getField(i));
                    }
                    for (int i = 0; i != this.numField2; ++i) {
                        t.setField(this.numField1 + i, tuple2.getField(i));
                    }
                    return t;
                }
            }
            this.tuple1 = this.child1.hasNext() ? this.child1.next() : null;
            child2.rewind();
        }
        return null;
    }
}
